[FJD-47] Configure additional blocks
fivejars/drupal_starterkit pull request #34
Opened 2024-04-11 08:47 UTC by david-storm

Jira issue:

Steps to review:
- [ ] login as admin
- [ ] Create a basic page
- [ ] Go to layout this page
- [ ] Click **add block**
Ensure that you can create following blocks:
- [ ] Image Carousel
- [ ] Banner
- [ ] Video
- [ ] Gallery (Photo/Video gallery)
- [ ] Webforms

2024-04-11 09:47 UTC, OleksandrRiumshyn requested changes

2024-04-11 09:47 UTC, OleksandrRiumshyn commented on config/install/core.entity_form_display.block_content.carousel_item.default.yml
> +        view_mode: default
use some separate view mode for thumbnail. for example media library

2024-04-11 09:47 UTC, OleksandrRiumshyn commented on config/install/core.entity_form_display.block_content.carousel.default.yml
> +    settings:
after adding items Block description is empty(looks like a bug)

2024-04-11 09:47 UTC, OleksandrRiumshyn commented on config/install/core.entity_form_display.block_content.carousel.default.yml
> +  field_item:
field is multiple, so I think we need better name. Maybe items or children

2024-04-11 09:47 UTC, OleksandrRiumshyn commented on config/install/field.field.block_content.carousel_item.field_image.yml
> +id: block_content.carousel_item.field_image
(optional) I think you could reuse media field

2024-04-11 09:47 UTC, OleksandrRiumshyn commented on config/install/field.field.block_content.video.field_video.yml
> +id: block_content.video.field_video
(optional) I think you could reuse media field

2024-04-11 09:47 UTC, OleksandrRiumshyn commented on config/install/field.storage.block_content.field_media.yml
> +id: block_content.field_media
The field is multiple so naming is no correct. Use please plural version instead ("medias")

2024-04-11 09:47 UTC, OleksandrRiumshyn commented on config/install/field.storage.block_content.field_video.yml
> +id: block_content.field_video
Could be combined with image field to one storage field_media

2024-04-11 09:47 UTC, OleksandrRiumshyn commented on config/install/block_content.type.carousel_item.yml
> +id: carousel_item
I'm not sure that we need block type here, maybe to use paragraphs would be easier solution. Let's discuss it together at Team sync call

2024-04-11 14:54 UTC, david-storm commented on config/install/core.entity_form_display.block_content.carousel.default.yml
> +    settings:
I added block description to form dispaly

2024-04-12 08:03 UTC, OleksandrRiumshyn approved these changes

2024-04-12 13:44 UTC, closed without merging

2024-04-12 13:44 UTC, OleksandrRiumshyn commented
Merged with other related branch